export const FORM_TYPE = 'FORM_TYPE';
export const SHOW_FORM_PANEL = 'SHOW_FORM_PANEL';
export const MODULE_ID = 'MODULE_ID';


export const SEND_CONFIG_LOADING = 'SEND_CONFIG_LOADING';
export const SEND_CONFIG_SUCCESS = 'SEND_CONFIG_SUCCESS';
export const SEND_CONFIG_FAIL = 'SEND_CONFIG_FAIL';

export const CREATE_USER_LOADING = 'CREATE_USER_LOADING';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';